### PR TITLE
hub ConnectionString via image parameters

### PR DESCRIPTION
**Pull request by ondrajodas**
Jira - https://keboola.atlassian.net/browse/COM-692

### CODE REVIEW

**Review by pivnicek — APPROVED** [review]
One question, if both are set it should use connectionString from imageParameters?

if connectionString from configParameters should override the one in imageParameters then 👎 :-) 

If so then cajk :-)

**Comment by ondrajodas** [comment]
@pivnicek yeah, eventHub writer must connect to one endpoint from the csas stacks, so it should use connectionString from imageParameters if set

**Comment by pivnicek** [comment]
@ondrajodas and not possible for user to override?  if not then cajk

**Comment by ondrajodas** [comment]
From Tomis information - `writer can write only to one environment so we need to set fix endpoint parameter to the writer`

**Comment by pivnicek** [comment]
cool, so imho this does that :-D

**Pull request merged**
